#!/usr/bin/bash

#[SAMPLE][DIR][NUMERIC][PREFIXES]
read -r -a array <<< $( ls -p | grep -v "/" | grep -E [0-9] | cut -d "_" -f "1" | tr "\n" " " )
#[CASE][EXCEPTION][NONE]
[ ${#array[@]} -eq 0 ] && { echo "0" ; exit 0 ; }
#[CASE][NORMAL][SORT]
read -r -a sorted <<< $( cd ~/Documents/engineering/research/math ; ./sortInts ${array[@]} )
#[SELECT][LAST][ELEMENT]
last=${sorted[-1]}
#[INCREMENT][PRINT][EXIT]
result=$(( $last + 1 ))
echo "$result"
exit 0 ;






# [INFO]
# Inspects current dir's files
# numeral prefix and returns
# the next in line.

# [USAGE]
# - takes no arguments
# - acts on desired dir
# - returns int of next
#   prefix

# [LIMITATIONS]
# - must be in the dir where it will check the files
# - any non-associated number-prefixed names will
#   make this produce false-positives
