#! /usr/bin/bash

while read line
do
	line_lc=${line,,}
	echo "$line_lc"
done < "${1:-/dev/stdin}"

# [INFO]
# Lower case capitalizes all read strings.
# Reads from stdin.
# Prints to stdout.
# Doesnt take parameters.
# 	[USECASES]
# 	toLower.sh < file1.txt
# 	toLower.sh
# [INFO]
